version: "3.9"

services:
  php:
    build: .
    
  nginx:
    image: "nginx:alpine"
    volumes: 
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./www/index.php:/var/www/index.php
    ports: 
      - 80:80
    command:  nginx-debug -g 'daemon off;'

