version: "3.9"

services:
  php:
    build: .
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://nginx | grep -c works > /dev/null "]
      interval: 5s
      timeout: 5s
      retries: 5
    
  nginx:
    image: "nginx:alpine"
    volumes: 
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./www/index.php:/var/www/index.php
    ports: 
      - 80:80
    command:  nginx-debug -g 'daemon off;'

